name: Lint

on:
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 18

jobs:
  run-linting:
    name: Run linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run code linting
        run: npm run lint

  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        env:
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          AUTH0_ID: ${{ secrets.AUTH0_ID }}
          AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
          TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
